name: Deployment-of-python-app
on: [push]
jobs:
  finaltask:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Detect secrets with Talisman in incoming commits
      uses: carhartl/talisman-secrets-scan-action@v1.0.1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint with pylint
      run: |
        python example.py